name: Deploy static site to EC2

on:
  push:
    branches: [ "main", "workflow_dispatch" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare SSH
        shell: bash
        run: |
          set -e
          mkdir -p "$HOME/.ssh"

          # Decode the base64 secret into id_rsa
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' | base64 --decode > "$HOME/.ssh/id_rsa"

          chmod 600 "$HOME/.ssh/id_rsa"
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> "$HOME/.ssh/known_hosts"

          echo "âœ… SSH key file created with $(wc -l < "$HOME/.ssh/id_rsa") lines" 


      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./
          target: /home/${{ secrets.EC2_USER }}/temp

      - name: Execute remote SSH commands to copy from temp to real folder
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo cp -r /home/${{ secrets.EC2_USER }}/temp/* /usr/site/
            sudo rm -rf /home/${{ secrets.EC2_USER }}/temp
            sudo nginx -t && sudo systemctl reload nginx
